version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - smart-traffic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Mock backend for testing
  mock-backend:
    image: mockserver/mockserver:latest
    ports:
      - "8000:1080"
    environment:
      MOCKSERVER_SERVER_PORT: 1080
      MOCKSERVER_LOG_LEVEL: INFO
    volumes:
      - ./mock-backend-config.json:/opt/mockserver/initializerJson/mockServerInitializer.json:ro
    networks:
      - smart-traffic
    restart: unless-stopped

networks:
  smart-traffic:
    driver: bridge

volumes:
  nginx_cache:
    driver: local
