apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-api
  namespace: traffic-ml
  labels:
    app: streaming-api
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streaming-api
  template:
    metadata:
      labels:
        app: streaming-api
        version: v1.0.0
    spec:
      containers:
      - name: streaming-api
        image: traffic-streaming-api:latest
        ports:
        - containerPort: 8002
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: REDIS_HOST
          value: "redis-service"
        - name: ML_API_URL
          value: "http://ml-api-service:8001"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /stream/stats
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /stream/stats
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: streaming-logs
          mountPath: /app/logs
      volumes:
      - name: streaming-logs
        emptyDir: {}
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-api-service
  namespace: traffic-ml
  labels:
    app: streaming-api
spec:
  selector:
    app: streaming-api
  ports:
  - name: http
    port: 8002
    targetPort: 8002
    protocol: TCP
  - name: websocket
    port: 8003
    targetPort: 8003
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: streaming-api-hpa
  namespace: traffic-ml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: streaming-api
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
